import type { DopamineLevel } from "./types";

export const songs: Record<DopamineLevel, string[]> = {
  1: [
    "macroblank01/macroblank1.mp3",
    "macroblank01/macroblank2.mp3",
    "macroblank01/macroblank3.mp3",
    "macroblank01/macroblank4.mp3",
    "macroblank01/macroblank5.mp3",
    "macroblank01/macroblank6.mp3",
  ],
  2: [
    "macroblank01/macroblank7.mp3",
    "macroblank01/macroblank8.mp3",
    "macroblank01/macroblank9.mp3",
    "macroblank01/macroblank10.mp3",
    "macroblank01/macroblank11.mp3",
  ],
  3: ["orion-cpp/distantrooms.mp3"],
  4: [
    "sewerslvt/21_Lolibox.mp3",
    "sewerslvt/22_SewerslvtWas_It_Weird_I_Listened_To_Im_God_By_Clams_Casino's_When_I_Lost_My_Virginity_(reupload).mp3",
    "sewerslvt/23_Sewerslvtsick,_twisted,_demented.mp3",
    "sewerslvt/24_SewerslvtMAKE_ME_SAD.mp3",
    "sewerslvt/25_Sewerslvtblissful_overdose.mp3",
    "sewerslvt/26_SewerslvtYandere_Complex.mp3",
    "sewerslvt/27_SewerslvtDown_The_Drain_(feat._Nurtheon).mp3",
    "sewerslvt/28_Sewerslvtthe_last_thing_she_sent_me.mp3",
    "sewerslvt/29_SewerslvtI_Really_Like_You_pt2.mp3",
    "sewerslvt/30_SewerslvtLooming.Sorrow.Descent.mp3",
    "sewerslvt/01_SewerslvtPretty_Cvnt.mp3",
    "sewerslvt/02_SewerslvtMr._Kill_Myself.mp3",
    "sewerslvt/03_SewerslvtNewlove.mp3",
    "sewerslvt/04_Sewerslvtinpeace.mp3",
    "sewerslvt/05_SewerslvtCyberia_lyr1.mp3",
  ],
  5: [
    "sewerslvt/06_SewerslvtLexapro_Delirium.mp3",
    "sewerslvt/07_AZALEA卒業ですね_(Sewerslvt_Remix).mp3",
    "sewerslvt/08_Bring_Me_The_HorizonDrown_(Sewerslvt_Remix).mp3",
    "sewerslvt/09_Sewerslvtgoodbye.mp3",
    "sewerslvt/10_LOONAHi_High_(Sewerslvt_Remix).mp3",
    "sewerslvt/11_SewerslvtEcifircas.mp3",
    "sewerslvt/12_SewerslvtThe_Grilled_Fish's_Ballad.mp3",
    "sewerslvt/13_SewerslvtSlowdeath.mp3",
    "sewerslvt/14_Sewerslvtinlove.mp3",
    "sewerslvt/15_SewerslvtJvnko_Loves_You.mp3",
    "sewerslvt/16_Sewerslvtwhatever.mp3",
    "sewerslvt/17_SewerslvtHopelessness.mp3",
    "sewerslvt/18_Sewerslvtself_destruction_worldwide_broadcast.mp3",
    "sewerslvt/19_Porter_RobinsonGet_Your_Wish_(Sewerslvt_Remix).mp3",
    "sewerslvt/20_Sewerslvtall_the_joy_In_life_was_gone_once_you_left.mp3",
  ],
};
